// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forms.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Forms module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder addOptionsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Forms.AddOptions");
		return builder;
	}

	public static void addOptions(IContext context)
	{
		addOptionsBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder adminDashboardCountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Forms.AdminDashboardCount");
		return builder;
	}

	public static forms.proxies.AdminDashboard adminDashboardCount(IContext context)
	{
		Object result = adminDashboardCountBuilder().execute(context);
		return result == null ? null : forms.proxies.AdminDashboard.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder backToHomeBuilder(
		forms.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Forms.BackToHome");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	public static void backToHome(
		IContext context,
		forms.proxies.Response _response
	)
	{
		backToHomeBuilder(
				_response
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder findCurrentMendixSSOUserBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Forms.FindCurrentMendixSSOUser");
		return builder;
	}

	public static mendixsso.proxies.MendixSSOUser findCurrentMendixSSOUser(IContext context)
	{
		Object result = findCurrentMendixSSOUserBuilder().execute(context);
		return result == null ? null : mendixsso.proxies.MendixSSOUser.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder newResponseBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Forms.NewResponse");
		return builder;
	}

	public static void newResponse(IContext context)
	{
		newResponseBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder saveOpionsBuilder(
		forms.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Forms.SaveOpions");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	public static void saveOpions(
		IContext context,
		forms.proxies.Response _response
	)
	{
		saveOpionsBuilder(
				_response
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder submitFormBuilder(
		forms.proxies.Response _response
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Forms.SubmitForm");
		builder = builder.withParam("Response", _response);
		return builder;
	}

	public static void submitForm(
		IContext context,
		forms.proxies.Response _response
	)
	{
		submitFormBuilder(
				_response
			)
			.execute(context);
	}
}
