// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package forms.proxies;

public class Response implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Forms.Response";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IdNumber("IdNumber"),
		CompletionTime("CompletionTime"),
		ResponseCompleted("ResponseCompleted"),
		AnswerAsString("AnswerAsString"),
		AnswerAsNumber("AnswerAsNumber"),
		AnswerAsTrueOfFalse("AnswerAsTrueOfFalse"),
		AnswerAsSingleChoice("AnswerAsSingleChoice"),
		AnswerAsDate("AnswerAsDate"),
		OptionsList("OptionsList"),
		Response_Option("Forms.Response_Option");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Response(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject)
	{
		if (responseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, responseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.responseMendixObject = responseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static forms.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new forms.proxies.Response(context, mendixObject);
	}

	public static forms.proxies.Response load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return forms.proxies.Response.initialize(context, mendixObject);
	}

	public static java.util.List<forms.proxies.Response> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> forms.proxies.Response.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of IdNumber
	 */
	public final java.lang.Long getIdNumber()
	{
		return getIdNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of IdNumber
	 */
	public final java.lang.Long getIdNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.IdNumber.toString());
	}

	/**
	 * Set value of IdNumber
	 * @param idnumber
	 */
	public final void setIdNumber(java.lang.Long idnumber)
	{
		setIdNumber(getContext(), idnumber);
	}

	/**
	 * Set value of IdNumber
	 * @param context
	 * @param idnumber
	 */
	public final void setIdNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long idnumber)
	{
		getMendixObject().setValue(context, MemberNames.IdNumber.toString(), idnumber);
	}

	/**
	 * @return value of CompletionTime
	 */
	public final java.lang.Integer getCompletionTime()
	{
		return getCompletionTime(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletionTime
	 */
	public final java.lang.Integer getCompletionTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CompletionTime.toString());
	}

	/**
	 * Set value of CompletionTime
	 * @param completiontime
	 */
	public final void setCompletionTime(java.lang.Integer completiontime)
	{
		setCompletionTime(getContext(), completiontime);
	}

	/**
	 * Set value of CompletionTime
	 * @param context
	 * @param completiontime
	 */
	public final void setCompletionTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer completiontime)
	{
		getMendixObject().setValue(context, MemberNames.CompletionTime.toString(), completiontime);
	}

	/**
	 * @return value of ResponseCompleted
	 */
	public final java.lang.Boolean getResponseCompleted()
	{
		return getResponseCompleted(getContext());
	}

	/**
	 * @param context
	 * @return value of ResponseCompleted
	 */
	public final java.lang.Boolean getResponseCompleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ResponseCompleted.toString());
	}

	/**
	 * Set value of ResponseCompleted
	 * @param responsecompleted
	 */
	public final void setResponseCompleted(java.lang.Boolean responsecompleted)
	{
		setResponseCompleted(getContext(), responsecompleted);
	}

	/**
	 * Set value of ResponseCompleted
	 * @param context
	 * @param responsecompleted
	 */
	public final void setResponseCompleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean responsecompleted)
	{
		getMendixObject().setValue(context, MemberNames.ResponseCompleted.toString(), responsecompleted);
	}

	/**
	 * @return value of AnswerAsString
	 */
	public final java.lang.String getAnswerAsString()
	{
		return getAnswerAsString(getContext());
	}

	/**
	 * @param context
	 * @return value of AnswerAsString
	 */
	public final java.lang.String getAnswerAsString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AnswerAsString.toString());
	}

	/**
	 * Set value of AnswerAsString
	 * @param answerasstring
	 */
	public final void setAnswerAsString(java.lang.String answerasstring)
	{
		setAnswerAsString(getContext(), answerasstring);
	}

	/**
	 * Set value of AnswerAsString
	 * @param context
	 * @param answerasstring
	 */
	public final void setAnswerAsString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String answerasstring)
	{
		getMendixObject().setValue(context, MemberNames.AnswerAsString.toString(), answerasstring);
	}

	/**
	 * @return value of AnswerAsNumber
	 */
	public final java.lang.Integer getAnswerAsNumber()
	{
		return getAnswerAsNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AnswerAsNumber
	 */
	public final java.lang.Integer getAnswerAsNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AnswerAsNumber.toString());
	}

	/**
	 * Set value of AnswerAsNumber
	 * @param answerasnumber
	 */
	public final void setAnswerAsNumber(java.lang.Integer answerasnumber)
	{
		setAnswerAsNumber(getContext(), answerasnumber);
	}

	/**
	 * Set value of AnswerAsNumber
	 * @param context
	 * @param answerasnumber
	 */
	public final void setAnswerAsNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer answerasnumber)
	{
		getMendixObject().setValue(context, MemberNames.AnswerAsNumber.toString(), answerasnumber);
	}

	/**
	 * @return value of AnswerAsTrueOfFalse
	 */
	public final java.lang.Boolean getAnswerAsTrueOfFalse()
	{
		return getAnswerAsTrueOfFalse(getContext());
	}

	/**
	 * @param context
	 * @return value of AnswerAsTrueOfFalse
	 */
	public final java.lang.Boolean getAnswerAsTrueOfFalse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AnswerAsTrueOfFalse.toString());
	}

	/**
	 * Set value of AnswerAsTrueOfFalse
	 * @param answerastrueoffalse
	 */
	public final void setAnswerAsTrueOfFalse(java.lang.Boolean answerastrueoffalse)
	{
		setAnswerAsTrueOfFalse(getContext(), answerastrueoffalse);
	}

	/**
	 * Set value of AnswerAsTrueOfFalse
	 * @param context
	 * @param answerastrueoffalse
	 */
	public final void setAnswerAsTrueOfFalse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean answerastrueoffalse)
	{
		getMendixObject().setValue(context, MemberNames.AnswerAsTrueOfFalse.toString(), answerastrueoffalse);
	}

	/**
	 * Get value of AnswerAsSingleChoice
	 * @param answerassinglechoice
	 */
	public final forms.proxies.ENUM_SingleChoice getAnswerAsSingleChoice()
	{
		return getAnswerAsSingleChoice(getContext());
	}

	/**
	 * @param context
	 * @return value of AnswerAsSingleChoice
	 */
	public final forms.proxies.ENUM_SingleChoice getAnswerAsSingleChoice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AnswerAsSingleChoice.toString());
		if (obj == null) {
			return null;
		}
		return forms.proxies.ENUM_SingleChoice.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AnswerAsSingleChoice
	 * @param answerassinglechoice
	 */
	public final void setAnswerAsSingleChoice(forms.proxies.ENUM_SingleChoice answerassinglechoice)
	{
		setAnswerAsSingleChoice(getContext(), answerassinglechoice);
	}

	/**
	 * Set value of AnswerAsSingleChoice
	 * @param context
	 * @param answerassinglechoice
	 */
	public final void setAnswerAsSingleChoice(com.mendix.systemwideinterfaces.core.IContext context, forms.proxies.ENUM_SingleChoice answerassinglechoice)
	{
		if (answerassinglechoice != null) {
			getMendixObject().setValue(context, MemberNames.AnswerAsSingleChoice.toString(), answerassinglechoice.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AnswerAsSingleChoice.toString(), null);
		}
	}

	/**
	 * @return value of AnswerAsDate
	 */
	public final java.util.Date getAnswerAsDate()
	{
		return getAnswerAsDate(getContext());
	}

	/**
	 * @param context
	 * @return value of AnswerAsDate
	 */
	public final java.util.Date getAnswerAsDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.AnswerAsDate.toString());
	}

	/**
	 * Set value of AnswerAsDate
	 * @param answerasdate
	 */
	public final void setAnswerAsDate(java.util.Date answerasdate)
	{
		setAnswerAsDate(getContext(), answerasdate);
	}

	/**
	 * Set value of AnswerAsDate
	 * @param context
	 * @param answerasdate
	 */
	public final void setAnswerAsDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date answerasdate)
	{
		getMendixObject().setValue(context, MemberNames.AnswerAsDate.toString(), answerasdate);
	}

	/**
	 * @return value of OptionsList
	 */
	public final java.lang.String getOptionsList()
	{
		return getOptionsList(getContext());
	}

	/**
	 * @param context
	 * @return value of OptionsList
	 */
	public final java.lang.String getOptionsList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OptionsList.toString());
	}

	/**
	 * Set value of OptionsList
	 * @param optionslist
	 */
	public final void setOptionsList(java.lang.String optionslist)
	{
		setOptionsList(getContext(), optionslist);
	}

	/**
	 * Set value of OptionsList
	 * @param context
	 * @param optionslist
	 */
	public final void setOptionsList(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String optionslist)
	{
		getMendixObject().setValue(context, MemberNames.OptionsList.toString(), optionslist);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Response_Option
	 */
	public final java.util.List<forms.proxies.Option> getResponse_Option() throws com.mendix.core.CoreException
	{
		return getResponse_Option(getContext());
	}

	/**
	 * @param context
	 * @return value of Response_Option
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<forms.proxies.Option> getResponse_Option(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<forms.proxies.Option> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Response_Option.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(forms.proxies.Option.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Response_Option
	 * @param response_option
	 */
	public final void setResponse_Option(java.util.List<forms.proxies.Option> response_option)
	{
		setResponse_Option(getContext(), response_option);
	}

	/**
	 * Set value of Response_Option
	 * @param context
	 * @param response_option
	 */
	public final void setResponse_Option(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<forms.proxies.Option> response_option)
	{
		var identifiers = response_option
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Response_Option.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return responseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final forms.proxies.Response that = (forms.proxies.Response) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
